version: "3.7"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - "6000:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password